### ISSUE TITLE
Authentication Page - request for modifications

### ISSUE THREAD

**Issue by HaddadTala** [ejp-rd-vp/vp-portal-issues#13] opened 2023-06-30 10:34 UTC
for auth.vp.ejprarediseases.org the following was requested:

a. to include logo of EJP RD at the header

b. Short explanation of login system (keycloack and LS-AAI)  (few sentences on ownership of those systems and what are they used for in the VP context: example: LifeScience Login is an authentication service provided by EOSC-Life. It enables researchers to use their home organisation credentials or community or other identities (e.g. Google, Linkedin, LS ID) to sign in and access data and services they need. It also allows service providers (both in academia and industry) to control and manage access rights of their users and create different access levels for research groups or international projects)
 
c. Way to go back to EJP VP homepage from auth page (a back arrow or home arrow?)

d. Prioritize the LS-AAI login over internal keycloack login (put it as the first option in the login page)

e. Add "Contact Us" button

**Comment by HaddadTala** [comment] 2023-06-30 10:35
@vabishaa @Ammarbr @kkr-ait

**Comment by Ammarbr** [comment] 2023-07-04 12:47
Thank you @HaddadTala  for submitting the issue!

We have successfully addressed all four points and I would like to inform you that the issue can now be marked as resolved. In regards to point D, instead of adding a new button, we have rectified the standard browser functionality. This means that you can simply click the "back button" in your browser, and you will be redirected back to the portal as intended.

[VP-PORTAL](https://vp.ejprarediseases.org/)

[LOGIN PAGE](https://auth.vp.ejprarediseases.org/auth/realms/ejp/protocol/openid-connect/auth?protocol=oauth2&response_type=code&access_type&client_id=discovery-portal&redirect_uri=https%3A%2F%2Fvp.ejprarediseases.org%2F&scope=openid%20profile%20email&state=HmPmt7qTCI&code_challenge_method=S256&code_challenge=xdls4djotFg-mDwPiuw2Xk5d5lWZPud6dMFqb_Hy5BM)

**Closed by Ammarbr** 2023-07-04 12:47 UTC
